nelmio_api_doc:
    documentation:
        info:
            title: My  API
            description: Documentaci√≥n de la Api 
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
